ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM prodo_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE USAGE ON SEQUENCES FROM prodo_app;

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM prodo_app;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM prodo_app;

DROP ROLE IF EXISTS prodo_app_user;
DROP ROLE IF EXISTS prodo_app;
